using SVGPathTwicker;

namespace SVGPathTweak.Tests
{
    public class SvgFileExtractorTests
    {
        private string _tempDir = string.Empty;

        [SetUp]
        public void Setup()
        {
            _tempDir = Path.Combine(Path.GetTempPath(), "SvgFileExtractorTests_" + Guid.NewGuid().ToString("N"));
            Directory.CreateDirectory(_tempDir);
        }

        [TearDown]
        public void TearDown()
        {
            if (Directory.Exists(_tempDir))
            {
                Directory.Delete(_tempDir, recursive: true);
            }
        }

        [Test]
        public async Task ReadsQuotingAndTagFormAndTransformVariants()
        {
            // covers: single vs double quoted attributes, self-closing vs open/close <path>,
            // decimal and single-argument translate(), and SVG2 CSS-property transform
            string svg = """
                <svg xmlns="http://www.w3.org/2000/svg">
                  <path id="A" d="m 0,0 10,0 0,10 z" transform="translate(5,7)"/>
                  <path id='B' d='m 0,0 5,5 z' transform='translate(139.99999,77.47527)'></path>
                  <path d="m 0,0 3,3 z" transform="translate(10)"/>
                  <path id="D" d="m 0,0 2,2 z" style="transform:translate(12px,8px)"/>
                </svg>
                """;
            await File.WriteAllTextAsync(Path.Combine(_tempDir, "sample.svg"), svg);

            SvgFileExtractor extractor = new(_tempDir);
            await extractor.Init();

            string csv = await File.ReadAllTextAsync(Path.Combine(_tempDir, "export_svg.csv"));
            string[] lines = csv.Split(Environment.NewLine, StringSplitOptions.RemoveEmptyEntries);
            // line 0 is the header
            Dictionary<string, string[]> rowsByName = lines.Skip(1)
                .Select(l => l.Split(';'))
                .ToDictionary(cols => cols[2].Trim('"'));

            Assert.Multiple(() =>
            {
                Assert.That(rowsByName, Contains.Key("A"), "double-quoted, self-closing path");
                Assert.That(rowsByName["A"][5], Is.EqualTo("5"), "Delta X");
                Assert.That(rowsByName["A"][6], Is.EqualTo("7"), "Delta Y");

                Assert.That(rowsByName, Contains.Key("B"), "single-quoted, open/close path");
                Assert.That(rowsByName["B"][5], Is.EqualTo("140"), "decimal translate x rounded to nearest");
                Assert.That(rowsByName["B"][6], Is.EqualTo("77"), "decimal translate y rounded to nearest");

                Assert.That(rowsByName, Contains.Key("path1"), "unnamed path gets an autogenerated name");
                Assert.That(rowsByName["path1"][5], Is.EqualTo("10"), "single-argument translate x");
                Assert.That(rowsByName["path1"][6], Is.EqualTo("0"), "single-argument translate implies y=0");

                Assert.That(rowsByName, Contains.Key("D"), "CSS-property transform (SVG2)");
                Assert.That(rowsByName["D"][5], Is.EqualTo("12"), "CSS transform translate x");
                Assert.That(rowsByName["D"][6], Is.EqualTo("8"), "CSS transform translate y");
            });
        }
    }
}
